apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value: "redis-service"
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        volumeMounts:
        - name: backend-content
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: backend-content
        configMap:
          name: backend-content
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  type: ClusterIP