apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Backend API</title>
    </head>
    <body>
        <h1>Backend API Service</h1>
        <p>This is the backend API responding from pod: <strong id="hostname"></strong></p>
        <p>Connected to Redis: <span id="redis-status">redis-service</span></p>
        <script>
            document.getElementById('hostname').textContent = window.location.hostname;
        </script>
    </body>
    </html>